/*
 * Copyright 2022 EngFlow Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */

package com.engflow.bazel.invocation.analyzer.options;

/**
 * Specifies what information about the analyzed profile is printed.
 *
 * <p>Modes are combinable for printing multiple categories of information.
 */
public enum Mode {
  /** Include all datum elements produced by DataProviders. */
  ALL_DATA,
  /**
   * Include any datum elements consumed by SuggestionProviders.
   *
   * <p>This option has no effect when ALL_DATA is specified.
   */
  USED_DATA,
  /**
   * Include all suggestions generated by SuggestionProviders.
   *
   * <p>This is the default mode if no mode is specified.
   */
  SUGGESTIONS
}
