java_test(
    name = "traceeventformat",
    srcs = glob(["**/*.java"]),
    test_class = "com.engflow.bazel.invocation.analyzer.traceeventformat.TraceEventFormatTestSuite",
    deps = [
        "//analyzer/java/com/engflow/bazel/invocation/analyzer/time",
        "//analyzer/java/com/engflow/bazel/invocation/analyzer/traceeventformat",
        "//third_party/gson",
        "//third_party/junit",
        "//third_party/truth",
    ],
)
